#日志记录
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
myyml:
  root: /home
  img: /uploaderPath/img
  name: n1,n2,n3
 
#mybatis配置
mybatis:
  #check-config-location: true
  #executor-type: batch
  type-aliases-package: com.nieyue.bean 
  mapper-locations: classpath:config/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel: true
    useGeneratedKeys: true  
    
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp 
  #mvc:
    #date-format: yyyy-MM-dd HH:mm:ss
  jackson: 
    #property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    date-format: yyyy-MM-dd HH:mm:ss 
    time-zone:  GMT+8
  session:
    store-type: none 
  profiles:
    active: dev
  datasource:
    name: master
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: liliu
  redis:
   # host: 118.190.133.146
    host: 127.0.0.1
    password: liliu
    port: 6379 
    timeout: 3000
    pool:
      min-idle: 50
      max-idle: 300
      max-active: 800
  rabbitmq:
    addresses: 118.190.133.146
    username: nieyue
    password: liliu
    listener:
      acknowledge-mode: manual
      retry:
        enabled: true
    
#    username: guest
#    password: guest
    virtual-host: /
    publisher-confirms: true
    
custom: 
  datasource:
    names: slave1
    slave1: 
      name: slave1
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test1
      #url: jdbc:mysql://114.215.70.214:3306/earn_turn_db
      username: root
      password: liliu
